/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.CategoryDao;
import dao.ProductDao;
import java.util.ArrayList;
import java.util.*;
import model.Category;
import model.Product;

/**
 *
 * @author dharm
 */
public class AddNewProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
        sSave.setEnabled(false);
    }
    
    public void validateFeilds()
    {
        String name = sName.getText();
        String price = sPrice.getText();
        if(!name.equals("")&&!price.equals(""))
            sSave.setEnabled(true);
        else {
            sSave.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        sCategory = new javax.swing.JComboBox<>();
        sPrice = new javax.swing.JTextField();
        sSave = new javax.swing.JButton();
        sClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add a new Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 21, 280, 50));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 18, 75, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 140, 41, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 190, 91, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 244, 41, -1));

        sName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sNameKeyReleased(evt);
            }
        });
        getContentPane().add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 137, 387, -1));

        sCategory.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(sCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 187, 387, -1));

        sPrice.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sPriceKeyReleased(evt);
            }
        });
        getContentPane().add(sPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 241, 387, -1));

        sSave.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sSave.setText("Save");
        sSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSaveActionPerformed(evt);
            }
        });
        sSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sSaveKeyReleased(evt);
            }
        });
        getContentPane().add(sSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 301, 75, -1));

        sClear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sClear.setText("Clear");
        sClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sClearActionPerformed(evt);
            }
        });
        sClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sClearKeyReleased(evt);
            }
        });
        getContentPane().add(sClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 301, 75, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smallbackground.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sSaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sSaveKeyReleased
        // TODO add your handling code here:
        validateFeilds();
    }//GEN-LAST:event_sSaveKeyReleased

    private void sClearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sClearKeyReleased
        // TODO add your handling code here:
        validateFeilds();  
    }//GEN-LAST:event_sClearKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> ar = CategoryDao.getAllRecords();
        Iterator<Category> itr = ar.iterator();
        while(itr.hasNext())
        {
            Category catobj = itr.next();
            sCategory.addItem(catobj.getName());
            
        }
                
                
    }//GEN-LAST:event_formComponentShown

    private void sSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSaveActionPerformed
        // TODO add your handling code here:
        Product pro = new Product();
        pro.setName(sName.getText());
        pro.setCategory(sCategory.getSelectedItem().toString());
        pro.setPrice(Integer.parseInt(sPrice.getText()));
        ProductDao.save(pro);
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_sSaveActionPerformed

    private void sClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_sClearActionPerformed

    private void sNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sNameKeyReleased
        // TODO add your handling code here:
        validateFeilds();
    }//GEN-LAST:event_sNameKeyReleased

    private void sPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sPriceKeyReleased
        // TODO add your handling code here:
        validateFeilds();
    }//GEN-LAST:event_sPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> sCategory;
    private javax.swing.JButton sClear;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sPrice;
    private javax.swing.JButton sSave;
    // End of variables declaration//GEN-END:variables
}
