/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;


import cafe.management.system.Admin.AdminHomepage;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;


/**
 *
 * @author dharm
 */
public class PlaceOrder extends javax.swing.JFrame {
    
    
    public int billId = 1;
    public int grandTotal = 0;
    public int productPrice = 0;
    public int productTotal = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    public String userEmail;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        
        userEmail = email;
        
        
        initComponents();
    }
    
    public void productNameByCategory(String category)
    {
        DefaultTableModel dtm =  (DefaultTableModel) tableCategory.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while(itr.hasNext())
        {
            Product productObj  = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
                
    }
    
    
    public void filterProductName(String name, String category)
    {
        DefaultTableModel dtm =  (DefaultTableModel) tableCategory.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getProductByName(category, name);
        Iterator<Product> itr = list.iterator();
        while(itr.hasNext())
        {
            Product productObj  = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
                
    }
    
    public void clearProductFeilds()
    {
        pName.setText("");
        pPrice.setText("");
        pQuantity.setValue(0);
        pTotal.setText("");
        btnAddToCart.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sMobile = new javax.swing.JTextField();
        sName = new javax.swing.JTextField();
        sEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        sSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pPrice = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGT = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        sGrandTotal = new javax.swing.JLabel();
        btnGenerateBill = new javax.swing.JButton();
        pQuantity = new javax.swing.JSpinner();
        Bid = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 76, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 125, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 106, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 146, -1));

        sMobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(sMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 177, -1));

        sName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 177, -1));

        sEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEmailActionPerformed(evt);
            }
        });
        getContentPane().add(sEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 177, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 124, -1, 24));

        sCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sCategoryMouseClicked(evt);
            }
        });
        sCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(sCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 159, 236, -1));

        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        tableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableCategoryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 286, 236, 383));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 199, -1, -1));

        sSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sSearchKeyReleased(evt);
            }
        });
        getContentPane().add(sSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 234, 236, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 199, 169, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 129, 144, -1));

        pName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 159, 231, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 199, -1, -1));

        pTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 233, 231, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 124, -1));

        pPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 159, 231, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, -1, -1));

        tableGT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        tableGT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableGT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 319, 551, 291));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Grand Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 634, -1, -1));

        sGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        sGrandTotal.setText("0000");
        getContentPane().add(sGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 634, -1, -1));

        btnGenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btnGenerateBill.setText("Generate Bill and Print");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, -1, -1));

        pQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pQuantityStateChanged(evt);
            }
        });
        getContentPane().add(pQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 233, 231, -1));

        Bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bid.setForeground(new java.awt.Color(255, 255, 255));
        Bid.setText("--");
        getContentPane().add(Bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 76, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        sEmail.setText(userEmail);
        billId = Integer.parseInt(BillDao.getId());
        Bid.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext())
        {
            Category categoryobj = itr.next();
            sCategory.addItem(categoryobj.getName());
        }
        String category = (String) sCategory.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_formComponentShown

    private void sSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sSearchKeyReleased
        // TODO add your handling code here:
        String name = sSearch.getText();
        String category = (String) sCategory.getSelectedItem();
        filterProductName(name, category);
    }//GEN-LAST:event_sSearchKeyReleased

    private void sCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sCategoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sCategoryMouseClicked

    private void tableCategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryMouseReleased
        // TODO add your handling code here:
        int idx = tableCategory.getSelectedRow();
        TableModel model = tableCategory.getModel();
        String productName = model.getValueAt(idx, 0).toString();
        Product product = ProductDao.getProductByNameAndSet(productName);
        pName.setText(product.getName());
        pPrice.setText(Integer.toString(product.getPrice()));
        productPrice = product.getPrice();
        productTotal =  productPrice;
        btnAddToCart.setEnabled(true);
        
    }//GEN-LAST:event_tableCategoryMouseReleased

    private void pQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pQuantityStateChanged
        // TODO add your handling code here:
        int qty = (Integer) pQuantity.getValue();
        if(qty<=1)
        {
            pQuantity.setValue(1);
            qty = 1;
        }
        productTotal = productPrice*qty;
        pTotal.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_pQuantityStateChanged

    private void sCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCategoryActionPerformed
        // TODO add your handling code here:
        String category = (String) sCategory.getSelectedItem();
        productNameByCategory(category);
        
    }//GEN-LAST:event_sCategoryActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String name = sName.getText();
        String price = pPrice.getText();
        String quantity = String.valueOf(pQuantity.getValue());
        DefaultTableModel dtm = (DefaultTableModel) tableGT.getModel();
        dtm.addRow(new Object[]{name, price, quantity, productTotal});
        grandTotal = grandTotal + productTotal;
        sGrandTotal.setText(String.valueOf(grandTotal));
        clearProductFeilds();
//        validate();

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        // TODO add your handling code here:
        
        String cusName = sName.getText();
        int cusMobile = Integer.parseInt(sMobile.getText());
        String cusEmail = sEmail.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String todayDate = dFormat.format(date);
        System.out.println(date);
        String total = String.valueOf(grandTotal);
        String createdBy = userEmail;
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setName(cusName);
        bill.setCreatedBy(createdBy);
        bill.setDate(todayDate);
        bill.setMobileNumber(cusMobile);
        bill.setEmail(cusEmail);
        bill.setTotal(total);
        
        String path = "D://";
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId +".pdf"));
            doc.open();
            Paragraph cafeName = new Paragraph("                                                                 XYZ Cafe\n");
            doc.add(cafeName);
            Paragraph starLine = new Paragraph("****************************************************************************************************************");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tBill ID: "+billId+"\nCustomer Name: "+cusName+"\nTotal Paid: "+grandTotal);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for(int i=0; i < tableGT.getRowCount();i++){
                String n = tableGT.getValueAt(i, 0).toString();
                String d = tableGT.getValueAt(i, 1).toString();
                String r = tableGT.getValueAt(i, 2).toString();
                String q = tableGT.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph thanksMsg = new Paragraph("Thank You,Please Visit Again");
            doc.add(thanksMsg);
            OpenPdf.openById(String.valueOf(billId));
            
            
            BillDao.save(bill);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void tableGTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGTMouseClicked
        // TODO add your handling code here:
        int index = tableGT.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model = tableGT.getModel();
            String total = model.getValueAt(index, 3).toString();
            grandTotal = grandTotal - Integer.parseInt(total);
            sGrandTotal.setText(String.valueOf(grandTotal));
            ((DefaultTableModel) tableGT.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_tableGTMouseClicked

    private void sEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bid;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pPrice;
    private javax.swing.JSpinner pQuantity;
    private javax.swing.JTextField pTotal;
    private javax.swing.JComboBox<String> sCategory;
    private javax.swing.JTextField sEmail;
    private javax.swing.JLabel sGrandTotal;
    private javax.swing.JTextField sMobile;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sSearch;
    private javax.swing.JTable tableCategory;
    private javax.swing.JTable tableGT;
    // End of variables declaration//GEN-END:variables

    private void when(boolean hasNext) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
