/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system.User;

import dao.UserDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author dharm
 */
public class ChangePassword extends javax.swing.JFrame {
    
    String email;
    String password1;
    String password2;
    
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }
     public ChangePassword(String thisEmail) {
        initComponents();
        email = thisEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sEmail = new javax.swing.JLabel();
        sPassword1 = new javax.swing.JPasswordField();
        sPassword2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        btnChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        sEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sEmail.setForeground(new java.awt.Color(255, 255, 255));
        sEmail.setText("-");
        sEmail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sEmailComponentShown(evt);
            }
        });
        getContentPane().add(sEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 460, -1));

        sPassword1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sPassword1KeyReleased(evt);
            }
        });
        getContentPane().add(sPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 460, -1));

        sPassword2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPassword2ActionPerformed(evt);
            }
        });
        sPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sPassword2KeyReleased(evt);
            }
        });
        getContentPane().add(sPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 460, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Re-Type Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, 110, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cafe_forgotPass.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        if(password1!=password2) JOptionPane.showMessageDialog(null, email);
       
        UserDAO.updateUser(email, password1);
        new UserLogin().setVisible(true);
        setVisible(false);
           
        
        
        
    }//GEN-LAST:event_btnChangeActionPerformed

    private void sPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sPassword1KeyReleased
        // TODO add your handling code here:
        password1 = sPassword1.getText();
    }//GEN-LAST:event_sPassword1KeyReleased

    private void sPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sPassword2KeyReleased
        // TODO add your handling code here:
        password2 = sPassword2.getText();
    }//GEN-LAST:event_sPassword2KeyReleased

    private void sEmailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sEmailComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_sEmailComponentShown

    private void sPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPassword2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        sEmail.setText(email);
        if(email==null)
        {
            JOptionPane.showMessageDialog(null, "Please log in with valid creds");
            setVisible(false);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit the Application??", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            // agar true hai toh
            System.exit(0);
            //            setVisible(false);
            //            new AdminLogin().setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel sEmail;
    private javax.swing.JPasswordField sPassword1;
    private javax.swing.JPasswordField sPassword2;
    // End of variables declaration//GEN-END:variables
}
