/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system.User;

import dao.UserDAO;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author dharm
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    String email;
    String mobileNumber;
    String name;
    String nickName;
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sMobileNumber = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sNickName = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        sEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEmailActionPerformed(evt);
            }
        });
        sEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sEmailKeyReleased(evt);
            }
        });
        getContentPane().add(sEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 530, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        sName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sNameKeyReleased(evt);
            }
        });
        getContentPane().add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 530, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        sMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMobileNumberActionPerformed(evt);
            }
        });
        sMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sMobileNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sMobileNumberKeyTyped(evt);
            }
        });
        getContentPane().add(sMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 530, -1));

        btnVerify.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btnVerify.setText("Verify and Proceed");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 240, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nick Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        sNickName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sNickName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNickNameActionPerformed(evt);
            }
        });
        sNickName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sNickNameKeyReleased(evt);
            }
        });
        getContentPane().add(sNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 530, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 110, 40));

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnClose.setText("Close");
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ForgotPasswordPage.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sMobileNumberActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        boolean check = UserDAO.isThere(email, name, mobileNumber, nickName);
        if(check==true)
        {
            new ChangePassword(email).setVisible(true);
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Check the Creds properly");
            
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void sNickNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNickNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNickNameActionPerformed

    private void sEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sEmailKeyReleased
        // TODO add your handling code here:
        email = sEmail.getText();
    }//GEN-LAST:event_sEmailKeyReleased

    private void sEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sEmailActionPerformed

    private void sNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sNameKeyReleased
        name = sName.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameKeyReleased

    private void sMobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sMobileNumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sMobileNumberKeyTyped

    private void sMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sMobileNumberKeyReleased
        // TODO add your handling code here:
        mobileNumber = sMobileNumber.getText();
    }//GEN-LAST:event_sMobileNumberKeyReleased

    private void sNickNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sNickNameKeyReleased
        // TODO add your handling code here:
        nickName = sNickName.getText();
        
    }//GEN-LAST:event_sNickNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField sEmail;
    private javax.swing.JTextField sMobileNumber;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sNickName;
    // End of variables declaration//GEN-END:variables
}
